### ISSUE TITLE
Identify and implement preferred node version manager

### ISSUE THREAD

**Issue by willclarktech** [LiskHQ/lisk-template#70]
### Expected behavior

We should recommend and use (via auxiliary files etc) whichever node version manager best suits our purposes overall. This issue involves creating a feature matrix for the various version managers available (`n`, `nvm`, `nenv`, `nodenv`...), including e.g. usage, activity, contribution status, on the basis of which we can make an informed decision.

### Actual behavior

A community member requested support for `nvm` at some point early in the project history so this became our de facto recommendation.

**Comment by willclarktech** [comment]
Closing due to lack of interest. We have `nvm` for now, we can reopen if anyone comes up with new and convincing arguments.

**Comment by nazarhussain** [comment]
@willclarktech I remember to have long discussion on this topic and we compared `nvm` and `nenv`. If you still remember it or have its reference. Please post to this issue for future reference.

**Comment by willclarktech** [comment]
@nazarhussain I don't know where that would be located (if anywhere), and I don't believe it contained any information that couldn't easily be reconstructed on demand.
