### ISSUE TITLE
Remove equal sign from package.json dependencies

### ISSUE THREAD

**Issue by Tosch110** [LiskHQ/lisk-template#90]
### Expected behavior

Dependencies should be listed with a specific version. Just plain the version in order to get sure it is the exact version.

E.g. 
```
"dependencies": {
		"babel-polyfill": "6.26.0",
	}
```

### Actual behavior

The version of the dependency contains an equal sign.

E.g.
```
"dependencies": {
		"babel-polyfill": "=6.26.0",
	}
```

### More Details

In the documentation of npm an equal sign does not exist. Therefore probably redundant:
https://docs.npmjs.com/files/package.json#dependencies

**Comment by willclarktech** [comment]
This should also update `.npmrc` to use `save-exact = true` instead of `save-prefix`.
