### ISSUE TITLE
Change Jenkinsfile to always deleteDir() on post build

### ISSUE THREAD

**Issue by shuse2** [LiskHQ/lisk-template#92]
### Expected behavior
Not being affected by the previous build.
```
post {
	always {
                 // archive whatever is needed for debug
		archiveArtifacts allowEmptyArchive: true, artifacts: 'logs/*'
                 // clean working space
                 deleteDir()
	}
}
```

### Actual behavior
- Some built result affects the next build

**Comment by willclarktech** [comment]
@fchavant Thoughts?

The reasoning so far has been that in the case of a failing build you might want to see what's there.

**Comment by Nazgolze** [comment]
@willclarktech indeed, that was my first thought too. We could go with always cleaning the workspace though and in the event that we need to see more, do a replay build and remove 'deleteDir' in the replay

**Comment by shuse2** [comment]
I think for `debug` purpose, we should specifically build with the result, or
```
archiveArtifacts allowEmptyArchive: true, artifacts: 'logs/*'
```
use this to archive whatever is needed
