### ISSUE TITLE
Add GitHub Welcome bot

### ISSUE THREAD

**Issue by michaeltomasik** [LiskHQ/lisk-template#96]
### Expected behavior
GitHub Welcome bot should be installed
https://github.com/apps/welcome
So it will answers when somebody creates PR or issue
### Actual behavior
There is none

**Comment by karmacoma** [comment]
Related to: https://github.com/LiskHQ/lisk-hub/issues/715

**Comment by willclarktech** [comment]
I've requested help on copy from @LindsaysDarkAlley

**Comment by willclarktech** [comment]
@michaeltomasik What value does this provide? In Lisk Hub it looks like it doesn't give the user much information that isn't already provided by the issue template or links GitHub shows contributors.
